name: CI

on:
  push:
  pull_request:
    branches: [ develop ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
      - uses: actions/checkout@v2

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
              
      - name: Build debug
        run: ./gradlew buildDebug
